name: Cold Start

on:
  schedule:
    - cron: "13,28,43,58 0-23 * * 1-5"
  workflow_dispatch:

jobs:
  cold-start:
    runs-on: ubuntu-latest

    steps:
      - name: Cold Start Server
        run: |
          curl -X GET "https://tradingbotwithemaandatr.onrender.com/coldStart" --fail
