name: Bot Runner

on:
  schedule:
    - cron: "0,15,30,45 0-23 * * 1-5"
  workflow_dispatch:

jobs:
  call-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Hit Bot Route
        run: |
          curl -X GET "https://tradingbotwithemaandatr.onrender.com/runBot" --fail
